services:
  # === СУЩЕСТВУЮЩАЯ СЛУЖБА ===
  web:
    image: php:8.3-apache
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    restart: unless-stopped


  exchange_rate_cron:
    build:
      dockerfile: Dockerfile
    container_name: exchange_rate_cron_service
    restart: unless-stopped
    environment:
      - TZ=Europe/Chisinau
